7
TEST
18

5
sailors
10
Mike Carey
9
40.3

5
sailors
21
David Dewitt
10
47.2

5
sailors
29
Tom Reps
7
39.1

5
sailors
31
Jeff Naughton
5
35.0

5
sailors
35
Miron Livny
7
37.6

5
sailors
37
Marv Solomon
10
48.9

5
sailors
39
Anne Condon
3
30.3

5
sailors
47
Charles Fischer
6
46.3

5
sailors
49
James Goodman
4
50.3

5
sailors
50
Mark Hill
5
35.2

5
sailors
53
Bob Holloway
9
53.6

5
sailors
54
Susan Horwitz
1
34.2

5
sailors
57
Yannis Ioannidis
8
40.2

5
sailors
59
Deborah Joseph
10
39.8

5
sailors
63
James Larus
9
30.3

5
sailors
64
Barton Miller
5
43.7

5
sailors
67
David Parter
1
99.9

5
sailors
69
Raghu Ramakrishnan
9
37.1

5
sailors
71
Guri Sohi
10
42.1

5
sailors
73
Prasoon Tiwari
8
39.2

5
sailors
75
Mary Vernon
7
43.1

5
sailors
79
David Wood
3
39.2

5
sailors
84
Mark Smucker
9
25.3

5
sailors
87
Martin Reames
10
24.1

5
boats
1
Onion
white

5
boats
2
Buckey
red

5
boats
3
Enterprise
blue

5
boats
4
Voyager
green

5
boats
5
Wisconsin
red

5
reserves
10
1
05/10/95

5
reserves
21
1
05/11/95

5
reserves
10
2
05/11/95

5
reserves
31
1
05/12/95

5
reserves
10
3
05/13/95

5
reserves
69
4
05/12/95

5
reserves
69
5
05/14/95

5
reserves
21
5
05/16/95

5
reserves
57
2
05/10/95

5
reserves
35
3
05/15/95

9
9
